<?php
namespace Mouf\Container\Definition;

/**
 * Generated by the ValueUtils::dumpValue method.
 */
class DumpedValue
{
    /**
     * PHP code to be prepended (usually creates the variable used in dumped value)
     * @var string
     */
    private $prependCode;

    /**
     * PHP code representing the value.
     * @var string
     */
    private $code;

    /**
     * DumpedValue constructor.
     * @param string $code PHP code representing the value.
     * @param string $prependCode PHP code to be prepended (usually creates the variable used in dumped value)
     */
    public function __construct($code, $prependCode = null)
    {
        $this->prependCode = $prependCode;
        $this->code = $code;
    }

    /**
     * PHP code to be prepended (usually creates the variable used in dumped value)
     * @return string
     */
    public function getPrependCode()
    {
        return $this->prependCode;
    }

    /**
     * PHP code representing the value.
     * @return string
     */
    public function getCode()
    {
        return $this->code;
    }
}